import {
  FormStatus,
  FieldType,
  Priority,
  ReportStatus,
  ReportVisibility,
  Permission,
  WorkType,
  EquipmentTags,
  IsActive,
  LoadType,
  EquipmentUsageType,
  EquipmentState,
  ApprovalStatus,
  FormTemplateCategory,
  FormTemplateStatus,
} from "@prisma/client";

export {
  FormStatus,
  FieldType,
  Priority,
  ReportStatus,
  ReportVisibility,
  Permission,
  WorkType,
  EquipmentTags,
  IsActive,
  LoadType,
  EquipmentUsageType,
  EquipmentState,
  ApprovalStatus,
  FormTemplateCategory,
  FormTemplateStatus,
};
