// Canonical union for timesheet status (not a Prisma enum)
export type TimeSheetStatus = "PENDING" | "APPROVED" | "DENIED";
import {
  FormStatus,
  FieldType,
  Priority,
  ReportStatus,
  ReportVisibility,
  Permission,
  WorkType,
  EquipmentTags,
  IsActive,
  LoadType,
  EquipmentUsageType,
  EquipmentState,
  ApprovalStatus,
  FormTemplateCategory,
  FormTemplateStatus,
  CreatedVia,
  materialUnit,
} from "../../prisma/generated/prisma/client";

export {
  FormStatus,
  FieldType,
  Priority,
  ReportStatus,
  ReportVisibility,
  Permission,
  WorkType,
  EquipmentTags,
  IsActive,
  LoadType,
  EquipmentUsageType,
  EquipmentState,
  ApprovalStatus,
  FormTemplateCategory,
  FormTemplateStatus,
  CreatedVia,
  materialUnit,
};
